### ISSUE TITLE
Pinned Tags not showing if left-menu is not pinned

### ISSUE THREAD

**Issue by B0F1B0** [papermerge/papermerge.js#1]
Pinned Tags only visilable, if the left menu-bar ist pinned. (picture 1). 
If the left menu-bar is not "pinned" the pinned tags are not showing (picture 2).
![papermerge_1](https://user-images.githubusercontent.com/39368417/143598708-9b4f4e18-01b2-486e-bdfb-3ce6d49e0d54.png)
![papermerge_2](https://user-images.githubusercontent.com/39368417/143598725-41afb272-5ee7-4a5c-881d-21062a4e4d8e.png)

"""
there we have the salad. its not a bug its a feature.
"""

**Comment by ciur** [comment]
@B0F1B0 
Thank you very much for opening this bug. This is frontend bug, so you opened the ticket in the right repository.

**Comment by ciur** [comment]
As of 2.1-alpha version the sidebar does not open on mouse hover. Instead sidebar is opened/closed only when user clicks sandwitch menu:
![sidebar-bug](https://user-images.githubusercontent.com/24827601/170635982-fb62cb7e-aa07-4424-9039-e924423ded5f.gif)

This bug is obsolete.
