### ISSUE TITLE
Automate feature

### ISSUE THREAD

**Issue by cosygarcia** [papermerge/papermerge.js#43]
I installed (via docker-compose) Papermerge Backend v2.1.4 and Frontend v2.1.2 but automate feature does not appear on the left menu.
How to enable it ?

Thanks

**Comment by ciur** [comment]
There is no such feature in 2.1. It will be ported in future versions though.

https://github.com/ciur/papermerge#papermerge-21-vs-papermerge-20

![no-automates-in-2-1](https://user-images.githubusercontent.com/24827601/223941977-7eb94372-32cb-4ab6-9f99-c30cb749a8a2.png)

**Comment by cosygarcia** [comment]
Thanks for your reply.

Is there a way to install 2.0.x via docker-composer ?

**Comment by ciur** [comment]
https://docs.papermerge.io/2.0.0/Installation/docker.html
